SET(CSPACK_SOURCES
cspack/cz/czclos.F
cspack/cz/czdumm.F
cspack/cz/czgeta.F
cspack/cz/czgetc.F
cspack/cz/czgtlg.F
cspack/cz/czopen.F
cspack/cz/czputa.F
cspack/cz/czputc.F
cspack/cz/czrand.F
cspack/cz/czrtim.F
cspack/cz/czstop.F
cspack/cz/czswap.F
cspack/cz/cztcp.F
cspack/fz/fzclos.F
cspack/fz/fzopen.F
cspack/fz/fzrmio.F
cspack/sz/chdir.F
cspack/sz/getcwd.F
cspack/sz/getdef.F
cspack/sz/setdef.F
cspack/sz/szcd.F
cspack/sz/szclos.F
cspack/sz/szinqr.F
cspack/sz/szls.F
cspack/sz/szmv.F
cspack/sz/szopen.F
cspack/sz/szpiaf.F
cspack/sz/szread.F
cspack/sz/szrewd.F
cspack/sz/szrite.F
cspack/sz/szrm.F
cspack/sz/szvers.F
cspack/xz/xzcd.F
cspack/xz/xzclos.F
cspack/xz/xzconv.F
cspack/xz/xzctof.F
cspack/xz/xzfinf.F
cspack/xz/xzftoc.F
cspack/xz/xzfzcp.F
cspack/xz/xzgeta.F
cspack/xz/xzgetb.F
cspack/xz/xzgetd.F
cspack/xz/xzgetf.F
cspack/xz/xzgetl.F
cspack/xz/xzgetp.F
cspack/xz/xzgetr.F
cspack/xz/xzgetx.F
cspack/xz/xzhrop.F
cspack/xz/xzinit.F
cspack/xz/xzinqr.F
cspack/xz/xzitoc.F
cspack/xz/xzlcat.F
cspack/xz/xzlcd.F
cspack/xz/xzlls.F
cspack/xz/xzlmv.F
cspack/xz/xzlogl.F
cspack/xz/xzlrm.F
cspack/xz/xzls.F
cspack/xz/xzlsys.F
cspack/xz/xzmv.F
cspack/xz/xzmvsd.F
cspack/xz/xzopen.F
cspack/xz/xzpref.F
cspack/xz/xzprot.F
cspack/xz/xzputa.F
cspack/xz/xzputb.F
cspack/xz/xzputd.F
cspack/xz/xzputf.F
cspack/xz/xzputl.F
cspack/xz/xzputp.F
cspack/xz/xzputr.F
cspack/xz/xzputx.F
cspack/xz/xzpwd.F
cspack/xz/xzread.F
cspack/xz/xzrewd.F
cspack/xz/xzrfrf.F
cspack/xz/xzrite.F
cspack/xz/xzrm.F
cspack/xz/xzrsys.F
cspack/xz/xzrtof.F
cspack/xz/xzrzcp.F
cspack/xz/xzrzop.F
cspack/xz/xzsver.F
cspack/xz/xzvers.F
cspack/xz/xzwrtm.F
)
