set(EPIO_SOURCES 
epio/code/epaddh.F
epio/code/epblin.F
epio/code/epbout.F
epio/code/epclos.F
epio/code/epdacr.F
epio/code/epdefu.F
epio/code/epdrop.F
epio/code/epend.F
epio/code/epeof.F
epio/code/eperrh.F
epio/code/epfhdr.F
epio/code/epfrd.F
epio/code/epgeta.F
epio/code/epgetc.F
epio/code/epgetw.F
epio/code/ephead.F
epio/code/epinit.F
epio/code/epiot.F
epio/code/epopestf.F
epio/code/epopevax.F
epio/code/epoutl.F
epio/code/epouts.F
epio/code/epread.F
epio/code/eprwnd.F
epio/code/epseta.F
epio/code/epsetc.F
epio/code/epsetw.F
epio/code/epstat.F
epio/code/epunit.F
epio/code/epupdh.F
epio/code/epuref.F
epio/util/blo16stf.F
epio/util/blo16stv.F
epio/util/blo16wva.F
epio/util/blo32wsf.F
epio/util/blo32wsv.F
epio/util/blo32wva.F
epio/util/blo8stf.F
epio/util/blo8stv.F
epio/util/blo8wib.F
epio/util/btswpstf.F
epio/util/btswpstv.F
epio/util/bun16stf.F
epio/util/bun16stv.F
epio/util/bun16wib.F
epio/util/bun32wsf.F
epio/util/bun32wsv.F
epio/util/bun32wva.F
epio/util/bun8stf.F
epio/util/bun8stv.F
epio/util/bun8wib.F
epio/util/cfrascun.F
epio/util/cfribmsf.F
epio/util/cfribmsv.F
epio/util/cfribmva.F
epio/util/ctoascun.F
epio/util/ctoibmva.F
epio/util/ctoibstf.F
epio/util/ctoibstv.F
epio/util/iwd16stf.F
epio/util/iwd16stv.F
epio/util/iwd16vax.F
epio/util/sfrascap.F
epio/util/sfrascvx.F
epio/util/stoascap.F
epio/util/stoascvx.F
epio/util/w16mvstf.F
epio/util/w16mvstv.F
)
