set(HBOOK_SOURCES 
hbook/chbook/halloc.c
hbook/chbook/hbpqry.c
hbook/chbook/hbvers.c
hbook/chbook/hmmap.c
hbook/chbook/hshm.c
hbook/code/h0mpw.F
hbook/code/h1evli.F
hbook/code/h2page.F
hbook/code/harith.F
hbook/code/harray.F
hbook/code/hauto.F
hbook/code/hbandx.F
hbook/code/hbandy.F
hbook/code/hbar2.F
hbook/code/hbarx.F
hbook/code/hbary.F
hbook/code/hbasft.F
hbook/code/hbcd.F
hbook/code/hbcdf.F
hbook/code/hbcdi.F
hbook/code/hbfun1.F
hbook/code/hbfun2.F
hbook/code/hbigbi.F
hbook/code/hbin.F
hbook/code/hbinsz.F
hbook/code/hblack.F
hbook/code/hbook1.F
hbook/code/hbook2.F
hbook/code/hbookb.F
hbook/code/hbookn.F
hbook/code/hbooknc.F
hbook/code/hbpro.F
hbook/code/hbprof.F
hbook/code/hbprox.F
hbook/code/hbproy.F
hbook/code/hbslix.F
hbook/code/hbsliy.F
hbook/code/hbstat.F
hbook/code/hbtit.F
hbook/code/hbuff.F
hbook/code/hbug.F
hbook/code/hcdir.F
hbook/code/hchnam.F
hbook/code/hcmom.F
hbook/code/hcompa.F
hbook/code/hconvol.F
hbook/code/hcopy.F
hbook/code/hcopym.F
hbook/code/hcopyn.F
hbook/code/hcopyr.F
hbook/code/hcopyt.F
hbook/code/hcopyu.F
hbook/code/hcorrl.F
hbook/code/hcovw.F
hbook/code/hcx.F
hbook/code/hcxy.F
hbook/code/hdcofl.F
hbook/code/hddir.F
hbook/code/hdelet.F
hbook/code/hderi1.F
hbook/code/hderi2.F
hbook/code/hderin.F
hbook/code/hderiv.F
hbook/code/hdexpo.F
hbook/code/hdipkl.F
hbook/code/hdummy.F
hbook/code/hdump.F
hbook/code/heleft.F
hbook/code/hermes.F
hbook/code/herror.F
hbook/code/hexda1.F
hbook/code/hexdat.F
hbook/code/hexist.F
hbook/code/hf1.F
hbook/code/hf1aut.F
hbook/code/hf1e.F
hbook/code/hf1n.F
hbook/code/hf2.F
hbook/code/hfact.F
hbook/code/hfc1.F
hbook/code/hfc2.F
hbook/code/hfcn.F
hbook/code/hfcnh.F
hbook/code/hfcnv.F
hbook/code/hfcnv1.F
hbook/code/hfcx.F
hbook/code/hfcxy.F
hbook/code/hfetc1.F
hbook/code/hfetch.F
hbook/code/hff1.F
hbook/code/hff2.F
hbook/code/hfidp.F
hbook/code/hfill.F
hbook/code/hfilpf.F
hbook/code/hfilpr.F
hbook/code/hfinam.F
hbook/code/hfind.F
hbook/code/hfinop.F
hbook/code/hfit.F
hbook/code/hfit1.F
hbook/code/hfitex.F
hbook/code/hfitf.F
hbook/code/hfitga.F
hbook/code/hfith.F
hbook/code/hfith1.F
hbook/code/hfithc.F
hbook/code/hfithn.F
hbook/code/hfitl.F
hbook/code/hfitn.F
hbook/code/hfitpo.F
hbook/code/hfits.F
hbook/code/hfitv.F
hbook/code/hfn.F
hbook/code/hfnov.F
hbook/code/hforma.F
hbook/code/hfpak1.F
hbook/code/hfpbug.F
hbook/code/hframe.F
hbook/code/hfumil.F
hbook/code/hfunc.F
hbook/code/hgaus.F
hbook/code/hgdire.F
hbook/code/hgetff.F
hbook/code/hgetfl.F
hbook/code/hgfit.F
hbook/code/hgive.F
hbook/code/hgiven.F
hbook/code/hgn.F
hbook/code/hgnf.F
hbook/code/hgnpar.F
hbook/code/hgstat.F
hbook/code/hhipar.F
hbook/code/hhxye.F
hbook/code/hi.F
hbook/code/hictoi.F
hbook/code/hid1.F
hbook/code/hid2.F
hbook/code/hidall.F
hbook/code/hidopt.F
hbook/code/hidpos.F
hbook/code/hie.F
hbook/code/hif.F
hbook/code/hij.F
hbook/code/hije.F
hbook/code/hijxy.F
hbook/code/hindex.F
hbook/code/hinpf.F
hbook/code/hinprx.F
hbook/code/hinq.F
hbook/code/hinteg.F
hbook/code/hipak1.F
hbook/code/histdo.F
hbook/code/histgo.F
hbook/code/hix.F
hbook/code/hkf1.F
hbook/code/hkf1q.F
hbook/code/hkf2.F
hbook/code/hkff1.F
hbook/code/hkff2.F
hbook/code/hkffi1.F
hbook/code/hkfi1.F
hbook/code/hkfil2.F
hbook/code/hkfill.F
hbook/code/hkfilpf.F
hbook/code/hkind.F
hbook/code/hknul1.F
hbook/code/hknuli.F
hbook/code/hlabel.F
hbook/code/hlabeq.F
hbook/code/hlabnb.F
hbook/code/hlattr.F
hbook/code/hlccmp.F
hbook/code/hldir.F
hbook/code/hldir1.F
hbook/code/hldir2.F
hbook/code/hldirt.F
hbook/code/hlgnxt.F
hbook/code/hlhcmp.F
hbook/code/hlimit.F
hbook/code/hllsq.F
hbook/code/hlnext.F
hbook/code/hlocat.F
hbook/code/hlogar.F
hbook/code/hlogpf.F
hbook/code/hloop.F
hbook/code/hlpos.F
hbook/code/hlshft.F
hbook/code/hlsort.F
hbook/code/hlsq.F
hbook/code/hlswap.F
hbook/code/hmachi.F
hbook/code/hmax.F
hbook/code/hmaxim.F
hbook/code/hmconv.F
hbook/code/hmdir.F
hbook/code/hmedia.F
hbook/code/hmin.F
hbook/code/hminim.F
hbook/code/hminui.F
hbook/code/hminut.F
hbook/code/hmonit.F
hbook/code/hmufit.F
hbook/code/hnoent.F
hbook/code/hnorma.F
hbook/code/hobsol.F
hbook/code/hoper1.F
hbook/code/hoper1a.F
hbook/code/hopera.F
hbook/code/hoptpf.F
hbook/code/houtpf.F
hbook/code/houtpu.F
hbook/code/hp1dim.F
hbook/code/hp1rot.F
hbook/code/hpaff.F
hbook/code/hpagsz.F
hbook/code/hpak.F
hbook/code/hpakad.F
hbook/code/hpake.F
hbook/code/hpakes.F
hbook/code/hparam.F
hbook/code/hparmn.F
hbook/code/hpath.F
hbook/code/hpchan.F
hbook/code/hpchar.F
hbook/code/hpcont.F
hbook/code/hpdir.F
hbook/code/hphist.F
hbook/code/hphs.F
hbook/code/hphst.F
hbook/code/hpkr32.F
hbook/code/hpolyn.F
hbook/code/hponce.F
hbook/code/hpr1h.F
hbook/code/hpr1v.F
hbook/code/hpr2.F
hbook/code/hprcha.F
hbook/code/hprcon.F
hbook/code/hprerr.F
hbook/code/hprfun.F
hbook/code/hprhis.F
hbook/code/hprint.F
hbook/code/hprlow.F
hbook/code/hprntu.F
hbook/code/hprof2.F
hbook/code/hproj1.F
hbook/code/hproj2.F
hbook/code/hprot.F
hbook/code/hprst.F
hbook/code/hprsta.F
hbook/code/hpsca.F
hbook/code/hpscat.F
hbook/code/hpstat.F
hbook/code/hpta.F
hbook/code/hptab.F
hbook/code/hptit.F
hbook/code/hrdir.F
hbook/code/hread.F
hbook/code/hrebin.F
hbook/code/hrename.F
hbook/code/hrep1.F
hbook/code/hreset.F
hbook/code/hrez0.F
hbook/code/hrndm.F
hbook/code/hrndm1.F
hbook/code/hrndm2.F
hbook/code/hrngpf.F
hbook/code/hrotat.F
hbook/code/hrval.F
hbook/code/hscale.F
hbook/code/hselbf.F
hbook/code/hseqnr.F
hbook/code/hsetbf.F
hbook/code/hsetpr.F
hbook/code/hsgz.F
hbook/code/hsifla.F
hbook/code/hsmoof.F
hbook/code/hspace.F
hbook/code/hspfun.F
hbook/code/hspli1.F
hbook/code/hspli2.F
hbook/code/hsquez.F
hbook/code/hstaf.F
hbook/code/hstar.F
hbook/code/hstati.F
hbook/code/hstelf.F
hbook/code/hsum.F
hbook/code/hsupim.F
hbook/code/hsupin.F
hbook/code/hsupis.F
hbook/code/htable.F
hbook/code/htfunc.F
hbook/code/htitle.F
hbook/code/hunpak.F
hbook/code/hunpke.F
hbook/code/huoptc.F
hbook/code/hupkrd.F
hbook/code/hwork.F
hbook/code/hwritf.F
hbook/code/hx.F
hbook/code/hxe.F
hbook/code/hxi.F
hbook/code/hxnorm.F
hbook/code/hxy.F
hbook/code/hxye.F
hbook/code/hxyij.F
hbook/hdiff/hbnsum.F
hbook/hdiff/hdbaop.F
hbook/hdiff/hdbcop.F
hbook/hdiff/hdbini.F
hbook/hdiff/hdbprf.F
hbook/hdiff/hdbsop.F
hbook/hdiff/hdiff.F
hbook/hdiff/hdiffb.F
hbook/hdiff/hgcont.F
hbook/hdiff/hlbino.F
hbook/hdiff/hlnfct.F
hbook/hglobal/hcreateg.F
hbook/hglobal/hfreeg.F
hbook/hglobal/hlnxtg.F
hbook/hglobal/hlnxtg1.F
hbook/hglobal/hmapg.F
hbook/hglobal/hopengbl.F
hbook/hglobal/hplisg.F
hbook/hglobal/hplisg1.F
hbook/hglobal/hresetg.F
hbook/hglobal/hresetg1.F
hbook/hglobal/hrez0g.F
hbook/hglobal/hrzing.F
hbook/hmcstat/hadjust.F
hbook/hmcstat/hfcnmin.F
hbook/hmcstat/hmcini.F
hbook/hmcstat/hmclnl.F
hbook/hmcstat/hmclno.F
hbook/hmcstat/hmcmll.F
hbook/hmerge/hmerg.F
hbook/hmerge/hmerge.F
hbook/hmerge/hmerge1.F
hbook/hmerge/hmerge2.F
hbook/hmerge/hmerge3.F
hbook/hmerge/hmergin.F
hbook/hmmap/hcreatem.F
hbook/hmmap/hlimap.F
hbook/hmmap/hlnxtm.F
hbook/hmmap/hlnxtm1.F
hbook/hmmap/hmapm.F
hbook/hmmap/hplism.F
hbook/hmmap/hplism1.F
hbook/hmmap/hrdirm.F
hbook/hmmap/hresetm.F
hbook/hmmap/hresetm1.F
hbook/hmmap/hrez0m.F
hbook/hmmap/hrzinm.F
hbook/hntup/hballoc.F
hbook/hntup/hbnam.F
hbook/hntup/hbnamc.F
hbook/hntup/hbname.F
hbook/hntup/hbnt.F
hbook/hntup/hbset.F
hbook/hntup/hcleft.F
hbook/hntup/hcompr.F
hbook/hntup/hcpoff.F
hbook/hntup/hfnt.F
hbook/hntup/hfnt1.F
hbook/hntup/hfnt2.F
hbook/hntup/hfntb.F
hbook/hntup/hgnt.F
hbook/hntup/hgnt1.F
hbook/hntup/hgnt2.F
hbook/hntup/hgntb.F
hbook/hntup/hgntbf.F
hbook/hntup/hgntf.F
hbook/hntup/hgntv.F
hbook/hntup/hgtdir.F
hbook/hntup/hicton.F
hbook/hntup/hitoc.F
hbook/hntup/hnbent.F
hbook/hntup/hnbfwr.F
hbook/hntup/hnbmin.F
hbook/hntup/hnbptr.F
hbook/hntup/hnbuf.F
hbook/hntup/hnbufd.F
hbook/hntup/hnbuff.F
hbook/hntup/hnbufr.F
hbook/hntup/hndesc.F
hbook/hntup/hnform.F
hbook/hntup/hnhdwr.F
hbook/hntup/hnmadr.F
hbook/hntup/hnmptr.F
hbook/hntup/hnmset.F
hbook/hntup/hnpart.F
hbook/hntup/hnsize.F
hbook/hntup/hntdel.F
hbook/hntup/hntdim.F
hbook/hntup/hntdup.F
hbook/hntup/hntget.F
hbook/hntup/hntgeti.F
hbook/hntup/hntmp.F
hbook/hntup/hntmpd.F
hbook/hntup/hntmpf.F
hbook/hntup/hntnam.F
hbook/hntup/hntnew.F
hbook/hntup/hntrd.F
hbook/hntup/hntrng.F
hbook/hntup/hntrset.F
hbook/hntup/hntsav.F
hbook/hntup/hnttok.F
hbook/hntup/hntvar.F
hbook/hntup/hntvdef.F
hbook/hntup/hntwrt.F
hbook/hntup/hparnt.F
hbook/hntup/hprnt.F
hbook/hntup/hprnts.F
hbook/hntup/hreco1.F
hbook/hntup/hreco2.F
hbook/hntup/hrecov.F
hbook/hntup/hrzfra.F
hbook/hntup/hrztoa.F
hbook/hntup/huwfun.F
hbook/hntup/hvxist.F
hbook/hntup/hwbnam.F
hbook/hntup/hwdecl.F
hbook/hntup/hwpdcl.F
hbook/hquad/hqbin.F
hbook/hquad/hqd.F
hbook/hquad/hqdd.F
hbook/hquad/hqddj.F
hbook/hquad/hqddjn.F
hbook/hquad/hqdj.F
hbook/hquad/hqdjn.F
hbook/hquad/hqdn.F
hbook/hquad/hqend.F
hbook/hquad/hqf.F
hbook/hquad/hqfer.F
hbook/hquad/hqfnl.F
hbook/hquad/hqfpl.F
hbook/hquad/hqgetf.F
hbook/hquad/hqgiv.F
hbook/hquad/hqin.F
hbook/hquad/hqinit.F
hbook/hquad/hqlif1.F
hbook/hquad/hqlif2.F
hbook/hquad/hqlif3.F
hbook/hquad/hqlsqc.F
hbook/hquad/hqlsqu.F
hbook/hquad/hqmnu.F
hbook/hquad/hqmxa1.F
hbook/hquad/hqmxa2.F
hbook/hquad/hqmxa3.F
hbook/hquad/hqmxb1.F
hbook/hquad/hqmxb2.F
hbook/hquad/hqmxb3.F
hbook/hquad/hqmxc1.F
hbook/hquad/hqmxc2.F
hbook/hquad/hqmxc3.F
hbook/hquad/hqmxli.F
hbook/hquad/hqout.F
hbook/hquad/hqpois.F
hbook/hquad/hqputf.F
hbook/hquad/hqsig.F
hbook/hquad/hqsig1.F
hbook/hquad/hqsig2.F
hbook/hquad/hqsig3.F
hbook/hquad/hqsiga.F
hbook/hquad/hqsolv.F
hbook/hquad/hqssv.F
hbook/hquad/hquad.F
hbook/hquad/hqwave.F
hbook/hquad/hqwrif.F
hbook/hquad/hqxi.F
hbook/hrz/hreadonedir.F
hbook/hrz/hrendc.F
hbook/hrz/hrendf.F
hbook/hrz/hrenid.F
hbook/hrz/hrfile.F
hbook/hrz/hrget.F
hbook/hrz/hrin.F
hbook/hrz/hrmake.F
hbook/hrz/hrmdir.F
hbook/hrz/hropen.F
hbook/hrz/hrout.F
hbook/hrz/hrput.F
hbook/hrz/hrsort.F
hbook/hrz/hrzcd.F
hbook/hrz/hrzin.F
hbook/hrz/hrzkey.F
hbook/hrz/hrzld.F
hbook/hrz/hrzout.F
hbook/hrz/hscr.F
)
