set(ZEBRA_SOURCES
zebra/dzebra/dzare1.F
zebra/dzebra/dzarea.F
zebra/dzebra/dzbkdv.F
zebra/dzebra/dzbkhd.F
zebra/dzebra/dzbkup.F
zebra/dzebra/dzbkxr.F
zebra/dzebra/dzchbk.F
zebra/dzebra/dzchst.F
zebra/dzebra/dzchv1.F
zebra/dzebra/dzchvc.F
zebra/dzebra/dzdata.F
zebra/dzebra/dzform.F
zebra/dzebra/dzforp.F
zebra/dzebra/dziopd.F
zebra/dzebra/dzioph.F
zebra/dzebra/dziopr.F
zebra/dzebra/dzmap.F
zebra/dzebra/dzopt.F
zebra/dzebra/dzshow.F
zebra/dzebra/dzshpr.F
zebra/dzebra/dzsnap.F
zebra/dzebra/dzstdv.F
zebra/dzebra/dzstla.F
zebra/dzebra/dzstor.F
zebra/dzebra/dzsurv.F
zebra/dzebra/dzswap.F
zebra/dzebra/dztext.F
zebra/dzebra/dztyp.F
zebra/dzebra/dzveri.F
zebra/dzebra/dzzero.F
zebra/dzebra/lzloc.F
zebra/dzebra/nzleft.F
zebra/dzebra/zdvcop.F
zebra/dzebra/zpage.F
zebra/fq/fzcffn.F
zebra/fq/fzcffx.F
zebra/fq/fzcopy.F
zebra/fq/fzendi.F
zebra/fq/fzendo.F
zebra/fq/fzficr.F
zebra/fq/fzfile.F
zebra/fq/fzhook.F
zebra/fq/fziacn.F
zebra/fq/fzialn.F
zebra/fq/fziasc.F
zebra/fq/fzichh.F
zebra/fq/fzicv.F
zebra/fq/fzidat.F
zebra/fq/fzidia.F
zebra/fq/fzidum.F
zebra/fq/fziffn.F
zebra/fq/fziffx.F
zebra/fq/fzilin.F
zebra/fq/fzimtb.F
zebra/fq/fzin.F
zebra/fq/fzinfo.F
zebra/fq/fzinxt.F
zebra/fq/fzipha.F
zebra/fq/fziphd.F
zebra/fq/fziphm.F
zebra/fq/fziphr.F
zebra/fq/fziprl.F
zebra/fq/fzirec.F
zebra/fq/fzirel.F
zebra/fq/fzitrn.F
zebra/fq/fzitrx.F
zebra/fq/fzlimi.F
zebra/fq/fzloc.F
zebra/fq/fzlogl.F
zebra/fq/fzmach.F
zebra/fq/fzmemo.F
zebra/fq/fzoaln.F
zebra/fq/fzoapk.F
zebra/fq/fzoasc.F
zebra/fq/fzocv.F
zebra/fq/fzodat.F
zebra/fq/fzoffn.F
zebra/fq/fzoffx.F
zebra/fq/fzon1.F
zebra/fq/fzon2.F
zebra/fq/fzon3.F
zebra/fq/fzon4.F
zebra/fq/fzon5.F
zebra/fq/fzon6.F
zebra/fq/fzophr.F
zebra/fq/fzorec.F
zebra/fq/fzotab.F
zebra/fq/fzotrn.F
zebra/fq/fzotrx.F
zebra/fq/fzotxt.F
zebra/fq/fzout.F
zebra/fq/fzrun.F
zebra/fq/fzudat.F
zebra/mq/mzattm.F
zebra/mq/mzbook.F
zebra/mq/mzcopy.F
zebra/mq/mzdiv.F
zebra/mq/mzdred.F
zebra/mq/mzdrop.F
zebra/mq/mzebra.F
zebra/mq/mzend.F
zebra/mq/mzflag.F
zebra/mq/mzinco.F
zebra/mq/mzinqd.F
zebra/mq/mzinqs.F
zebra/mq/mzlift.F
zebra/mq/mzlink.F
zebra/mq/mzlint.F
zebra/mq/mzlogl.F
zebra/mq/mzmaps.F
zebra/mq/mzmark.F
zebra/mq/mzneed.F
zebra/mq/mzpaw.F
zebra/mq/mzpudx.F
zebra/mq/mzpush.F
zebra/mq/mzrepl.F
zebra/mq/mzstor.F
zebra/mq/mzvers.F
zebra/mq/mzvolm.F
zebra/mq/mzwork.F
zebra/mqg/mzfgap.F
zebra/mqg/mzgar1.F
zebra/mqg/mzgarb.F
zebra/mqg/mzgsta.F
zebra/mqg/mzmove.F
zebra/mqg/mzrelb.F
zebra/mqg/mzrell.F
zebra/mqg/mzrelx.F
zebra/mqg/mztabc.F
zebra/mqg/mztabf.F
zebra/mqg/mztabh.F
zebra/mqg/mztabm.F
zebra/mqg/mztabr.F
zebra/mqg/mztabs.F
zebra/mqg/mztabx.F
zebra/mqg/mzwipe.F
zebra/mqs/lzfid.F
zebra/mqs/lzfidh.F
zebra/mqs/lzhead.F
zebra/mqs/lzscan.F
zebra/mqs/mzchln.F
zebra/mqs/mzchls.F
zebra/mqs/mzchnb.F
zebra/mqs/mzdvac.F
zebra/mqs/mzfdiv.F
zebra/mqs/mzform.F
zebra/mqs/mziobk.F
zebra/mqs/mziocf.F
zebra/mqs/mzioch.F
zebra/mqs/mziocr.F
zebra/mqs/mziotc.F
zebra/mqs/mzixco.F
zebra/mqs/mzneig.F
zebra/mqs/mzresv.F
zebra/mqs/mzsdiv.F
zebra/mqs/mzxref.F
zebra/mqs/mzxrpr.F
zebra/mqs/mzxrup.F
zebra/mqv/zvauto.F
zebra/mqv/zvautu.F
zebra/mqv/zvautx.F
zebra/mqv/zvauty.F
zebra/mqv/zvdo1.F
zebra/mqv/zvdo2.F
zebra/mqv/zvdobk.F
zebra/mqv/zvdola.F
zebra/mqv/zverif.F
zebra/mqv/zvfpri.F
zebra/qend/zabend.F
zebra/qend/zend.F
zebra/qend/zfatal.F
zebra/qend/zfatam.F
zebra/qend/zphase.F
zebra/qend/zpostm.F
zebra/qend/ztell.F
zebra/qend/ztelus.F
zebra/qutil/izbcd.F
zebra/qutil/izbcdt.F
zebra/qutil/izbcdv.F
zebra/qutil/izchav.F
zebra/qutil/izhnum.F
zebra/qutil/lzbyt.F
zebra/qutil/lzfind.F
zebra/qutil/lzfval.F
zebra/qutil/lzlast.F
zebra/qutil/lzlong.F
zebra/qutil/nzbank.F
zebra/qutil/nzfind.F
zebra/qutil/nzlong.F
zebra/qutil/qnext.F
zebra/qutil/zhtoi.F
zebra/qutil/zitoh.F
zebra/qutil/zkrak.F
zebra/qutil/zkrakn.F
zebra/qutil/znumid.F
zebra/qutil/zpress.F
zebra/qutil/zshunt.F
zebra/qutil/zsort.F
zebra/qutil/zsorth.F
zebra/qutil/zsorti.F
zebra/qutil/zsorv.F
zebra/qutil/zsorvh.F
zebra/qutil/zsorvi.F
zebra/qutil/ztopsy.F
zebra/rz/rzallo.F
zebra/rz/rzcdir.F
zebra/rz/rzchcy.F
zebra/rz/rzclos.F
zebra/rz/rzcop1.F
zebra/rz/rzcopy.F
zebra/rz/rzdate.F
zebra/rz/rzdelk.F
zebra/rz/rzdelt.F
zebra/rz/rzdlok.F
zebra/rz/rzend.F
zebra/rz/rzexpd.F
zebra/rz/rzfdir.F
zebra/rz/rzfile.F
zebra/rz/rzfree.F
zebra/rz/rzfrf1.F
zebra/rz/rzfrfz.F
zebra/rz/rzhfra.F
zebra/rz/rzhook.F
zebra/rz/rzhtoa.F
zebra/rz/rzin.F
zebra/rz/rzink.F
zebra/rz/rzinpa.F
zebra/rz/rzins.F
zebra/rz/rziodo.F
zebra/rz/rziphd.F
zebra/rz/rzkeep.F
zebra/rz/rzkeyd.F
zebra/rz/rzkeys.F
zebra/rz/rzldi1.F
zebra/rz/rzldir.F
zebra/rz/rzlinc.F
zebra/rz/rzlind.F
zebra/rz/rzllok.F
zebra/rz/rzlock.F
zebra/rz/rzlogl.F
zebra/rz/rzmake.F
zebra/rz/rzmdir.F
zebra/rz/rzmods.F
zebra/rz/rzndir.F
zebra/rz/rzobkn.F
zebra/rz/rzopen.F
zebra/rz/rzophd.F
zebra/rz/rzout.F
zebra/rz/rzpaff.F
zebra/rz/rzpass.F
zebra/rz/rzpath.F
zebra/rz/rzprnk.F
zebra/rz/rzpurf.F
zebra/rz/rzpurg.F
zebra/rz/rzquot.F
zebra/rz/rzrdir.F
zebra/rz/rzread.F
zebra/rz/rzrenk.F
zebra/rz/rzrtop.F
zebra/rz/rzsame.F
zebra/rz/rzsave.F
zebra/rz/rzscan.F
zebra/rz/rzstat.F
zebra/rz/rzstrip.F
zebra/rz/rzstrir.F
zebra/rz/rztof1.F
zebra/rz/rztofz.F
zebra/rz/rzused.F
zebra/rz/rzvcyc.F
zebra/rz/rzver1.F
zebra/rz/rzver2.F
zebra/rz/rzveri.F
zebra/rz/rzvers.F
zebra/rz/rzvin.F
zebra/rz/rzvout.F
zebra/rz/rzwrt.F
)
